default: &default
  adapter: postgis
  encoding: utf8

development:
  <<: *default
  database: partners_api_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
  database: partners_api_test
